[build-system]
requires = [
    "setuptools>=56",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
addopts = "-vvv -ra -q --html=results/report.html --self-contained-html"
